### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by cirocosta** [cirocosta/docker-git-http#6]
```sh
#correct
git clone http://localhost:8080/myrepo.git    
Cloning into 'myrepo'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (3/3), done.
```

instead of `80` should use `8080`

**Comment by szschaler** [comment]
Yes, I had stumbled over this one, too :-) In particular, your documentation still points to using `/initial/` as a prefix for inital repositories when they get placed directly at the root of the URL namespace.

**Comment by cirocosta** [comment]
Hi Steffen! I just pushed a commit addressing that, I hope now it's good 😁  

Thanks for noticing! 

Have a good one 👍

**Comment by szschaler** [comment]
Much better :-) Will this also make its way onto docker-hub?

Many thanks,

Steffen

**Comment by szschaler** [comment]
Sorry, my bad. Just noticed that the documentation has already been updated there, too. 

Has the image also been updated? It seems that tag `latest` still points to a 5-month old image (see also issue #9)?

**Comment by cirocosta** [comment]
oh, forgot to do it 😁  just updated there https://hub.docker.com/r/cirocosta/gitserver-http/tags/

**Comment by szschaler** [comment]
Many thanks. Looks like I cannot close issues, so assume you will do this.

**Comment by cirocosta** [comment]
np 😁  thaanks!
