### ISSUE TITLE
Latest commit not on Docker registry?

### ISSUE THREAD

**Issue by szschaler** [cirocosta/docker-git-http#9]
Hi,

I've just been playing with your nice Docker image and keep getting `/usr/local/bin/entrypoint: line 52: cd: /var/lib/initial: No such file or directory`. The line number and error suggest that the latest master version (commit sha 65304b47381780e73f332ed2e954a019822ec77c) hasn't made it onto the Docker registry, as that seems to fix this issue.

Many thanks,

Steffen

**Comment by cirocosta** [comment]
Just pushed a new version https://hub.docker.com/r/cirocosta/gitserver-http/tags/ 😁

**Comment by szschaler** [comment]
Many thanks,

Steffen
